version: '3.8'

services:
  kryptokrona-service:
    image: ghcr.io/kryptokrona/kryptokrona:c070f49
    container_name: kryptokrona-service
    command: >
      /bin/sh -c " ./src/kryptokrona-service"
    ports:
      - "10000:10000"
      - "20000:20000"
    networks:
      xkrnet:
        ipv4_address: 172.10.1.1

  kryptokrona-walletapi:
    image: ghcr.io/kryptokrona/kryptokrona:c070f49
    container_name: kryptokrona-walletapi
    command: >
      /bin/sh -c " ./src/wallet-api"
    ports:
      - "10001:10001"
      - "20001:20001"
    networks:
      xkrnet:
        ipv4_address: 172.10.1.2

networks:
  xkrnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.10.1.0/16"