blank_issues_enabled: true
contact_links:
  - name: Kryptokrona Kotlin SDK Discussions
    url: https://github.com/kryptokrona/kryptokrona-kotlin-sdk/discussions
    about: Please ask and answer usage-related questions here.