title: Kryptokrona Java SDK Documentation

theme: jekyll-theme-cayman

author: Marcus Cvjeticanin

social-network-links:
  email: "mjovanc@protonmail.com"
  rss: true
  github: kryptokrona
  twitter: kryptokrona
  reddit: kryptokrona
  instagram: kryptokrona
  telegram: kryptokrona
  linkedin: kryptokrona

share-links-active:
  twitter: true
  facebook: true
  linkedin: true