name: Kryptokrona SDK Main Pipeline

on:
  push:
    branches:
      - master

jobs:
  clean:
    name: Clean
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up OpenJDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Clean
        run: ./gradlew clean

  assemble:
    name: Assemble
    runs-on: ubuntu-latest
    needs: [ clean ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up OpenJDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Assemble
        run: ./gradlew assemble

  static-code-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    needs: [ assemble ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up OpenJDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Checking Style
        run: ./gradlew checkstyleMain

      - name: Checking Duplicated Code
        run: ./gradlew cpdCheck

      - name: Checking Bugs
        run: ./gradlew spotbugsMain

      - name: Checking Code Standard
        run: ./gradlew pmdMain

#  unit-test:
#    name: Unit Test
#    runs-on: ubuntu-latest
#    needs: [ static-code-analysis ]
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up OpenJDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: 'gradle'
#
#      - name: Compile Java Test Code
#        run: ./gradlew compileTestJava
#
#      - name: Test Classes
#        run: ./gradlew testClasses







#TODO: add stage to build javadoc ./gradlew javadoc and publish to github.io